import subprocess

_ALLOWED_EXECUTABLES = frozenset({
    "cat", "head", "tail", "grep", "sed", "awk", "cut", "sort", "uniq",
    "wc", "tr", "fold", "fmt", "nl", "tac", "rev", "paste", "join",
    "split", "csplit", "expand", "unexpand", "colrm", "column",
    "strings", "diff", "cmp", "comm", "patch", "pr", "od", "hexdump",
    "base64", "basenc", "iconv", "recode", "tee", "xargs",
    "find", "locate", "which", "whereis", "file", "stat", "readlink",
    "realpath", "dirname", "basename", "mktemp", "mkstemp",
    "seq", "yes", "shuf", "factor", "numfmt", "date", "printf",
    "echo", "test", "true", "false", "expr", "bc", "dc",
    "python3", "python", "perl", "ruby", "lua",
    "git", "git-rev-parse", "git-log", "git-diff", "git-show",
    "git-status", "git-branch", "git-tag", "git-config",
    "curl", "wget", "http", "jq", "yq",
    "openssl", "ssh-keygen", "ssh-keyscan", "gpg", "gpgv",
    "tar", "gzip", "gunzip", "bzip2", "bunzip2", "xz", "unxz",
    "zip", "unzip", "zipinfo", "zcat", "bzcat", "xzcat",
    "md5sum", "sha1sum", "sha256sum", "sha512sum", "cksum", "sum",
    "ls", "dir", "vdir", "pwd", "cd", "touch", "mkdir", "rmdir",
    "cp", "mv", "rm", "ln", "chmod", "chown", "chgrp",
    "df", "du", "free", "uptime", "uname", "hostname", "whoami",
    "id", "groups", "users", "who", "w", "last", "lastlog",
    "ps", "pgrep", "pkill", "pidof", "kill", "killall",
    "top", "htop", "vmstat", "iostat", "mpstat", "sar",
    "netstat", "ss", "ip", "ifconfig", "route", "arp", "iw",
    "ping", "traceroute", "tracepath", "mtr", "dig", "nslookup",
    "host", "whois", "nmap", "nc", "socat",
    "systemctl", "service", "chkconfig", "update-rc.d",
    "journalctl", "dmesg", "logger", "logrotate",
    "crontab", "at", "batch", "nice", "renice", "nohup", "screen",
    "tmux", "script", "scriptreplay", "tty", "stty", "setterm",
    "clear", "reset", "tput", "infocmp", "tic", "toe",
    "man", "apropos", "whatis", "help", "info", "pydoc", "perldoc",
    "vim", "vi", "nano", "emacs", "ed", "ex", "sed", "awk",
    "less", "more", "most", "pg", "view",
    "grep", "egrep", "fgrep", "rg", "ag", "ack", "pt",
    "sort", "tsort", "comm", "uniq", "count", "tally",
    "cut", "paste", "join", "split", "csplit", "divide",
    "tr", "expand", "unexpand", "detab", "entab",
    "fmt", "fold", "wrap", "unwrap", "par", "columns",
    "nl", "rn", "cat", "tac", "rev", "rotate",
    "head", "tail", "body", "init", "last", "butlast",
    "wc", "count", "length", "size", "bytes", "chars", "words", "lines",
    "md5", "sha1", "sha256", "sha512", "crc32", "adler32",
    "uuencode", "uudecode", "xxencode", "xxdecode", "binhex",
    "quoted-printable", "base32", "base64url", "base85", "ascii85",
    "urlencode", "urldecode", "htmlescape", "htmlunescape",
    "xmlescape", "xmlunescape", "jsonescape", "jsonunescape",
    "shellescape", "shellunescape", "regexescape", "regexunescape",
    "unicode", "ascii", "utf8", "utf16", "utf32", "latin1", "cp1252",
    "hex", "oct", "bin", "dec", "radix", "base", "convert",
    "encrypt", "decrypt", "sign", "verify", "hash", "hmac",
    "compress", "decompress", "deflate", "inflate", "gzip", "gunzip",
    "bzip", "bunzip", "lzma", "unlzma", "xz", "unxz", "zstd", "unzstd",
    "lz4", "unlz4", "lzo", "unlzo", "lzop", "unlzop", "lzf", "unlzf",
    "snappy", "unsnappy", "brotli", "unbrotli",
    "csv", "tsv", "ssv", "psv", "json", "yaml", "xml", "html", "toml",
    "ini", "cfg", "conf", "properties", "env", "dotenv",
    "sql", "sqlite3", "psql", "mysql", "mongo", "redis-cli",
    "docker", "podman", "kubectl", "helm", "terraform", "ansible",
    "vagrant", "packer", "consul", "vault", "nomad", "waypoint",
    "aws", "gcloud", "azure", "az", "doctl", "linode-cli",
    "npm", "yarn", "pnpm", "node", "npx", "deno", "bun",
    "pip", "pip3", "poetry", "conda", "mamba", "virtualenv", "venv",
    "pytest", "unittest", "nose", "tox", "nox", "coverage",
    "flake8", "pylint", "mypy", "black", "isort", "autopep8",
    "bandit", "safety", "pip-audit", "dependabot",
    "gcc", "g++", "clang", "clang++", "make", "cmake", "ninja",
    "cargo", "rustc", "rustup", "go", "gofmt", "golint",
    "javac", "java", "jar", "mvn", "gradle", "sbt",
    "ruby", "gem", "bundle", "rake", "irb", "erb",
    "php", "composer", "pear", "pecl",
    "swift", "swiftc", "xcodebuild", "carthage", "cocoapods",
    "dotnet", "msbuild", "nuget", "fsharp", "fsharpc",
    "rscript", "r", "julia", "matlab", "octave", "scilab",
    "psql", "pg_dump", "pg_restore", "createdb", "dropdb",
    "mysql", "mysqldump", "mysqladmin", "mongosh", "mongodump",
    "redis-cli", "redis-benchmark", "memcached-tool",
    "sqlite3", "sqlcipher", "dbish", "sqsh", "tsql",
    "ldapsearch", "ldapadd", "ldapmodify", "ldapdelete",
    "smbclient", "rpcclient", "net", "wbinfo", "ntlm",
    "kinit", "klist", "kdestroy", "ktutil", "kvno",
    "aklog", "afslog", "tokens", "unlog",
    "skey", "otp", "google-authenticator", "oathtool",
    "pass", "gopass", "keepassxc-cli", "bitwarden", "bw",
    "secret-tool", "keyctl", "keyring", "kwalletcli",
    "ssh", "ssh-add", "ssh-agent", "ssh-copy-id", "ssh-keyscan",
    "scp", "sftp", "rsync", "rclone", "ncftp", "lftp",
    "telnet", "ftp", "tftp", "rexec", "rlogin", "rsh",
    "slogin", "sftp-server", "scp-server",
    "stunnel", "openssl", "certtool", "gnutls-cli", "gnutls-serv",
    "curl", "wget", "httpie", "xh", "aria2c", "axel", "lftp",
    "lynx", "w3m", "links", "elinks", "browsh",
    "sendmail", "postfix", "exim", "mail", "mailx", "mutt",
    "alpine", "pine", "elm", "nmh", "mh",
    "procmail", "formail", "maildrop", "deliver", "dovecot",
    "spamassassin", "spamc", "razor-admin", "pyzor",
    "dkim-genkey", "dkim-sign", "dkim-verify", "opendkim",
    "dmarc", "spf", "dnssec", "dig", "delv", "drill",
    "named-checkconf", "named-checkzone", "rndc", "nsupdate",
    "host", "nslookup", "whois", "jwhois", "ripe", "arin",
    "geoiplookup", "geoip", "mmdblookup", "maxmind",
    "tcpdump", "tshark", "wireshark", "dumpcap", "capinfos",
    "ngrep", "tcpflow", "tcptrace", "tcpreplay", "tcprewrite",
    "nmap", "masscan", "zmap", "unicornscan",
    "hping", "hping3", "nping", "fragroute", "fragrouter",
    "ettercap", "etterfilter", "etterlog", "arpspoof", "dnsspoof",
    "sslstrip", "sslsniff", "mitmproxy", "burpsuite",
    "airmon-ng", "airodump-ng", "aireplay-ng", "aircrack-ng",
    "wifite", "reaver", "bully", "pixiewps",
    "john", "hashcat", "hydra", "medusa", "ncrack", "crowbar",
    "sqlmap", "nikto", "dirb", "gobuster", "wfuzz", "ffuf",
    "metasploit", "msfconsole", "msfvenom", "armitage",
    "beef", "setoolkit", "social-engineer-toolkit",
    "veil", "empire", "powershell-empire", "starkiller",
    "cobaltstrike", "brute-ratel", "sliver", "havoc",
    "mimikatz", "rubeus", "sharpkatz", " safetykatz",
    "bloodhound", "sharphound", "azurehound",
    "neo4j", "cypher-shell", "apoc", "gds",
    "nuclei", "subfinder", "assetfinder", "amass", "findomain",
    "httpx", "naabu", "notify", "chaos", "cloudlist",
    "waybackurls", "gau", "hakrawler", "katana",
    "dalfox", "xsstrike", "xsser", "commix",
    "liffy", "shellshock", "shocker", "heartbleed",
    "dirtycow", "cve", "exploitdb", "searchsploit",
    "msfrop", "ropgadget", "ropper", "angr", "pwntools",
    "checksec", "pwncheck", "libc-database",
    "one_gadget", "formatstr", "heapdump",
    "volatility", "rekall", "memprocfs", "avml",
    "lime", "fmem", "pcileech", "memprocfs",
    "yara", "yarac", "yara-python", "plaso", "log2timeline",
    "autopsy", "sleuthkit", "tsk", "fls", "ils", "mactime",
    "bulk_extractor", "scalpel", "foremost", "photorec",
    "testdisk", "ddrescue", "dd_rescue", "safecopy",
    "hashdeep", "md5deep", "sha256deep", "tigerdeep",
    "ssdeep", "sdhash", "mrsh-v2", "fbhash",
    "rabin2", "radare2", "rizin", "cutter", "iaito",
    "ghidra", "ida", "ida64", "binaryninja", "hopper",
    "retdec", "snowman", "decompiler", "dewolf",
    "angr-management", "binja", "gef", "pwndbg", "peda",
    "lldb", "gdb", "cgdb", "ddd", "valgrind", "callgrind",
    "cachegrind", "helgrind", "drd", "massif",
    "perf", "oprofile", "gprof", "ltrace", "strace", "ftrace",
    "sysdig", "sysdig-inspect", " Falco",
    "auditctl", "ausearch", "aureport", "autrace",
    "ausearch", "aulast", "aulastlog", "auvirt",
    "logwatch", "logcheck", "swatch", "fail2ban",
    "denyhosts", "sshguard", "crowdsec", "cscli",
    "osquery", "osqueryi", "kolide",
    "wazuh", "wazuh-manager", "wazuh-agent",
    "suricata", "suricata-update", "suricatasc",
    "zeek", "bro", "broctl", "zeekctl",
    "snort", "barnyard2", "pulledpork", "snort2lua",
    "clamav", "clamscan", "freshclam", "clamd",
    "rkhunter", "chkrootkit", "lynis", "tiger",
    "aide", "samhain", "tripwire", "ossec",
    "openscap", "oscap", "scap-workbench", "scap-security-guide",
    "nessus", "openvas", "gvm", "greenbone",
    "nexpose", "insightvm", "qualys", "rapid7",
    "burpsuite", "zap", "owasp-zap", "arachni", "w3af",
    "skipfish", "ratproxy", "paros", "webscarab",
    "vega", "wapiti", "watobo", "netsparker",
    "acunetix", "appscan", "detectify", "probely",
    "snyk", "whitesource", "blackduck", "checkmarx",
    "sonarqube", "sonar-scanner", "fortify",
    "veracode", "contrast", "immuniweb", "detectify",
    "hackerone", "bugcrowd", "synack", "intigriti",
    "cobalt", "detectify", "probely", "intruder",
    "securecodebox", "kube-hunter", "kube-bench",
    "trivy", "grype", "snyk-container", "anchore",
    "clair", "dagda", "falco", "sysdig-secure",
    "opa", "conftest", "gatekeeper", "kyverno",
    "kubescape", "kubesec", "kube-score",
    "helm", "chartmuseum", "chart-verifier",
    "argocd", "flux", "flagger", "spinnaker",
    "tekton", "jenkins", "gitlab-runner", "github-actions",
    "circleci", "travis", "appveyor", "azure-pipelines",
    "buildkite", "drone", "concourse", "spinnaker",
    "terraform", "terragrunt", "atlantis", "tfsec",
    "checkov", "terrascan", "semgrep", "regula",
    "pulumi", "cdktf", "cdk8s", "crossplane",
    "ansible", "ansible-playbook", "ansible-vault",
    "molecule", "testinfra", "pytest-testinfra",
    "salt", "salt-call", "salt-minion", "salt-master",
    "puppet", "facter", "hiera", "bolt",
    "chef", "knife", "ohai", "inspec", "cinc",
    "vagrant", "packer", "consul", "vault", "nomad",
    "boundary", "waypoint", "serf", "envconsul",
    "consul-template", "levant", "consul-esm",
    "traefik", "envoy", "istio", "linkerd", "consul-connect",
    "caddy", "nginx", "apachectl", "httpd", "lighttpd",
    "haproxy", "varnishd", "squid", "trafficserver",
    "memcached", "redis-server", "rabbitmqctl", "kafka",
    "elasticsearch", "kibana", "logstash", "beats",
    "prometheus", "alertmanager", "grafana", "loki",
    "jaeger", "zipkin", "tempo", "otelcol",
    "fluentd", "fluent-bit", "vector", "filebeat",
    "metricbeat", "packetbeat", "heartbeat", "auditbeat",
    "telegraf", "influxd", "ch
