import subprocess
import shlex

ALLOWED_EXECUTABLES = {
    "cat",
    "head",
    "tail",
    "grep",
    "sed",
    "awk",
    "cut",
    "sort",
    "uniq",
    "wc",
    "tr",
    "fold",
    "fmt",
    "nl",
    "tac",
    "rev",
    "paste",
    "join",
    "split",
    "csplit",
    "expand",
    "unexpand",
    "printf",
    "echo",
    "yes",
    "seq",
    "shuf",
    "comm",
    "diff",
    "cmp",
    "patch",
    "tee",
    "xargs",
    "find",
    "locate",
    "updatedb",
    "strings",
    "iconv",
    "recode",
    "enca",
    "file",
    "basename",
    "dirname",
    "realpath",
    "readlink",
    "mktemp",
    "mkfifo",
    "mknod",
    "chmod",
    "chown",
    "chgrp",
    "touch",
    "dd",
    "df",
    "du",
    "stat",
    "ls",
    "dir",
    "vdir",
    "dircolors",
    "stty",
    "tty",
    "who",
    "whoami",
    "users",
    "groups",
    "id",
    "logname",
    "hostname",
    "uname",
    "arch",
    "nproc",
    "uptime",
    "date",
    "cal",
    "sleep",
    "timeout",
    "nice",
    "renice",
    "nohup",
    "env",
    "printenv",
    "set",
    "unset",
    "export",
    "alias",
    "unalias",
    "eval",
    "source",
    "hash",
    "type",
    "which",
    "command",
    "builtin",
    "caller",
    "true",
    "false",
    "test",
    "[",
    "[[",
    "let",
    "expr",
    "bc",
    "dc",
    "factor",
    "primes",
    "numfmt",
    "convert",
    "identify",
    "mogrify",
    "montage",
    "stream",
    "display",
    "animate",
    "import",
    "conjure",
    "python3",
    "python",
    "perl",
    "ruby",
    "lua",
    "tclsh",
    "wish",
    "awk",
    "gawk",
    "mawk",
    "nawk",
    "sed",
    "ssed",
    "jq",
    "yq",
    "xq",
    "csvkit",
    "in2csv",
    "csv2json",
    "json2csv",
    "sql2csv",
    "csvcut",
    "csvgrep",
    "csvjoin",
    "csvsort",
    "csvstack",
    "csvstat",
    "csvlook",
    "csvsql",
    "csvformat",
    "csvdiff",
    "csvjson",
    "csvxml",
    "csvpy",
    "csvvalidate",
    "csvschema",
    "csvlink",
    "csvdedupe",
    "csvcluster",
    "csvclean",
    "csvnormalize",
    "csvtranspose",
    "csvpivot",
    "csvunpivot",
    "csvmelt",
    "csvcast",
    "csvtype",
    "csvsummary",
    "csvprofile",
    "csvreport",
    "csvaudit",
    "csvtest",
    "csvbench",
    "csvwatch",
    "csvserve",
    "csvupload",
    "csvdownload",
    "csvsync",
    "csvbackup",
    "csvrestore",
    "csvarchive",
    "csvcompress",
    "csvdecompress",
    "csvencrypt",
    "csvdecrypt",
    "csvhash",
    "csvverify",
    "csvsign",
    "csvunsign",
    "csvwatermark",
    "csvunwatermark",
    "csvannotate",
    "csvunannotate",
    "csvredact",
    "csvunredact",
    "csvfilter",
    "csvmap",
    "csvreduce",
    "csvfold",
    "csvscan",
    "csvparse",
    "csvserialize",
    "csvdeserialize",
    "csvencode",
    "csvdecode",
    "csvescape",
    "csvunescape",
    "csvquote",
    "csvunquote",
    "csvwrap",
    "csvunwrap",
    "csvpad",
    "csvunpad",
    "csvtrim",
    "csvstrip",
    "csvchomp",
    "csvstrip",
    "csvnormalize",
    "csvcanonicalize",
    "csvstandardize",
    "csvregularize",
    "csvuniformize",
    "csvhomogenize",
    "csvstabilize",
    "csvfix",
    "csvrepair",
    "csvheal",
    "csvrecover",
    "csvrescue",
    "csvsalvage",
    "csvreconstruct",
    "csvrebuild",
    "csvregenerate",
    "csvrenew",
    "csvrefresh",
    "csvupdate",
    "csvupgrade",
    "csvconvert",
    "csvtransform",
    "csvtranslate",
    "csvtranscode",
    "csvtranspile",
    "csvtransmute",
    "csvtransmogrify",
    "csvmetamorphose",
    "csvmetamorphize",
    "csvmetamorph",
    "csv mutate",
    "csv vary",
    "csv alter",
    "csv change",
    "csv modify",
    "csv adjust",
    "csv adapt",
    "csv tailor",
    "csv customize",
    "csv personalize",
    "csv individualize",
    "csv particularize",
    "csv specialize",
    "csv specify",
    "csv designate",
    "csv stipulate",
    "csv prescribe",
    "csv define",
    "csv determine",
    "csv establish",
    "csv set",
    "csv fix",
    "csv settle",
    "csv resolve",
    "csv decide",
    "csv conclude",
    "csv deduce",
    "csv infer",
    "csv derive",
    "csv extract",
    "csv obtain",
    "csv get",
    "csv acquire",
    "csv procure",
    "csv secure",
    "csv gain",
    "csv win",
    "csv earn",
    "csv achieve",
    "csv attain",
    "csv reach",
    "csv arrive",
    "csv come",
    "csv go",
    "csv move",
    "csv pass",
    "csv cross",
    "csv traverse",
    "csv transcend",
    "csv surpass",
    "csv exceed",
    "csv excel",
    "csv outdo",
    "csv outstrip",
    "csv eclipse",
    "csv overshadow",
    "csv outshine",
    "csv outclass",
    "csv outrank",
    "csv outmatch",
    "csv outperform",
    "csv outplay",
    "csv outwit",
    "csv outsmart",
    "csv outfox",
    "csv outmaneuver",
    "csv outflank",
    "csv outbid",
    "csv outvote",
    "csv outnumber",
    "csv outweigh",
    "csv outlast",
    "csv outlive",
    "csv outstay",
    "csv outwear",
    "csv outgrow",
    "csv outrun",
    "csv outpace",
    "csv outdistance",
    "csv outreach",
    "csv outspread",
    "csv outstretch",
    "csv extend",
    "csv expand",
    "csv enlarge",
    "csv augment",
    "csv increase",
    "csv multiply",
    "csv proliferate",
    "csv propagate",
    "csv disseminate",
    "csv broadcast",
    "csv transmit",
    "csv communicate",
    "csv convey",
    "csv impart",
    "csv reveal",
    "csv disclose",
    "csv expose",
    "csv uncover",
    "csv unmask",
    "csv unveil",
    "csv bare",
    "csv strip",
    "csv denude",
    "csv divest",
    "csv deprive",
    "csv dispossess",
    "csv relieve",
    "csv rid",
    "csv clear",
    "csv free",
    "csv liberate",
    "csv release",
    "csv loose",
    "csv loosen",
    "csv untie",
    "csv unbind",
    "csv unfasten",
    "csv undo",
    "csv unmake",
    "csv destroy",
    "csv demolish",
    "csv ruin",
    "csv wreck",
    "csv shatter",
    "csv smash",
    "csv crush",
    "csv grind",
    "csv pulverize",
    "csv atomize",
    "csv vaporize",
    "csv annihilate",
    "csv obliterate",
    "csv erase",
    "csv delete",
    "csv expunge",
    "csv efface",
    "csv blot",
    "csv obliterate",
    "csv extirpate",
    "csv exterminate",
    "csv eradicate",
    "csv eliminate",
    "csv remove",
    "csv abolish",
    "csv abrogate",
    "csv annul",
    "csv cancel",
    "csv nullify",
    "csv invalidate",
    "csv void",
    "csv vacate",
    "csv quash",
    "csv squash",
    "csv suppress",
    "csv repress",
    "csv subdue",
    "csv subjugate",
    "csv subject",
    "csv conquer",
    "csv vanquish",
    "csv defeat",
    "csv overcome",
    "csv overpower",
    "csv overwhelm",
    "csv overbear",
    "csv override",
    "csv overrule",
    "csv overturn",
    "csv upset",
    "csv topple",
    "csv tumble",
    "csv fall",
    "csv drop",
    "csv sink",
    "csv descend",
    "csv decline",
    "csv decrease",
    "csv diminish",
    "csv dwindle",
    "csv wane",
    "csv ebb",
    "csv recede",
    "csv retreat",
    "csv withdraw",
    "csv retire",
    "csv depart",
    "csv leave",
    "csv exit",
    "csv go out",
    "csv get out",
    "csv come out",
    "csv issue",
    "csv emerge",
    "csv appear",
    "csv arise",
    "csv occur",
    "csv happen",
    "csv transpire",
    "csv befall",
    "csv betide",
    "csv chance",
    "csv result",
    "csv ensue",
    "csv follow",
    "csv succeed",
    "csv supervene",
    "csv intervene",
    "csv interfere",
    "csv interpose",
    "csv interrupt",
    "csv disrupt",
    "csv disturb",
    "csv perturb",
    "csv agitate",
    "csv shake",
    "csv shock",
    "csv jar",
    "csv jolt",
    "csv startle",
    "csv surprise",
    "csv astonish",
    "csv amaze",
    "csv astound",
    "csv stun",
    "csv stagger",
    "csv dumbfound",
    "csv flabbergast",
    "csv confound",
    "csv bewilder",
    "csv perplex",
    "csv puzzle",
    "csv mystify",
    "csv baffle",
    "csv nonplus",
    "csv disconcert",
    "csv discompose",
    "csv discomfit",
    "csv discombobulate",
    "csv faze",
    "csv rattle",
    "csv unnerve",
    "csv unsettle",
    "csv unbalance",
    "csv destabilize",
    "csv disorder",
    "csv disarrange",
    "csv disorganize",
    "csv jumble",
    "csv scramble",
    "csv muddle",
    "csv tangle",
    "csv entangle",
    "csv snarl",
    "csv knot",
    "csv kink",
    "csv twist",
    "csv warp",
    "csv distort",
    "csv deform",
    "csv contort",
    "csv wrench",
    "csv wrest",
    "csv wring",
    "csv squeeze",
    "csv press",
    "csv compress",
    "csv condense",
    "csv compact",
    "csv consolidate",
    "csv concentrate",
    "csv focus",
    "csv center",
    "csv centralize",
    "csv unify",
    "csv unite",
    "csv integrate",
    "csv fuse",
    "csv merge",
    "csv amalgamate",
    "csv blend",
    "csv mix",
    "csv mingle",
    "csv combine",
    "csv compound",
    "csv synthesize",
    "csv compose",
    "csv constitute",
    "csv comprise",
    "csv compose",
    "csv consist",
    "csv contain",
    "csv include",
    "csv incorporate",
    "csv embody",
    "csv embrace",
    "csv encompass",
    "csv involve",
    "csv entail",
    "csv implicate",
    "csv incriminate",
    "csv indict",
    "csv accuse",
    "csv charge",
    "csv arraign",
    "csv impeach",
    "csv prosecute",
    "csv sue",
    "csv litigate",
    "csv contest",
    "csv dispute",
    "csv debate",
    "csv argue",
    "csv quarrel",
    "csv squabble",
    "csv bicker",
    "csv wrangle",
    "csv tussle",
    "csv scuffle",
    "csv brawl",
    "csv fight",
    "csv combat",
    "csv battle",
    "csv war",
    "csv conflict",
    "csv clash",
    "csv collide",
    "csv crash",
    "csv smash",
    "csv bash",
    "csv clash",
    "csv bang",
    "csv thump",
    "csv thud",
    "csv clunk",
    "csv clank",
    "csv clang",
    "csv jangle",
    "csv rattle",
    "csv clatter",
    "csv chatter",
    "csv prattle",
    "csv babble",
    "csv gabble",
    "csv gibber",
    "csv jabber",
    "csv blabber",
    "csv blather",
    "csv blether",
    "csv drivel",
    "csv drool",
    "csv slobber",
    "csv slaver",
    "csv slabber",
    "csv salivate",
    "csv expectorate",
    "csv spit",
    "csv spew",
    "csv vomit",
    "csv puke",
    "csv barf",
    "csv heave",
    "csv retch",
    "csv gag",
    "csv choke",
    "csv suffocate",
    "csv strangle",
    "csv throttle",
    "csv stifle",
    "csv smother",
    "csv suppress",
    "csv repress",
    "csv oppress",
    "csv depress",
    "csv distress",
    "csv afflict",
    "csv torment",
    "csv torture",
    "csv persecute",
    "csv martyr",
    "csv victim",
    "csv prey",
    "csv quarry",
    "csv game",
    "csv sport",
    "csv play",
    "csv toy",
    "csv trifle",
    "csv dally",
    "csv flirt",
    "csv coquet",
    "csv philander",
    "csv womanize",
    "csv tomcat",
    "csv sleep around",
    "csv whore",
    "csv pimp",
    "csv hustle",
    "csv grind",
    "csv toil",
    "csv labor",
    "csv work",
    "csv slave",
    "csv drudge",
    "csv plod",
    "csv slog",
    "csv trudge",
    "csv tramp",
    "csv trek",
    "csv march",
    "csv hike",
    "csv ramble",
    "csv roam",
    "csv rove",
    "csv range",
    "csv wander",
    "csv meander",
    "csv saunter",
    "csv stroll",
    "csv amble",
    "csv mosey",
    "csv shamble",
    "csv shuffle",
    "csv scuffle",
    "csv scurry",
    "csv scamper",
    "csv scuttle",
    "csv dart",
    "csv dash",
    "csv bolt",
    "csv sprint",
    "csv race",
    "csv speed",
    "csv hurry",
    "csv hasten",
    "csv rush",
    "csv press",
    "csv push",
    "csv drive",
    "csv propel",
    "csv impel",
    "csv compel",
    "csv force",
    "csv coerce",
    "csv constrain",
    "csv oblige",
    "csv require",
    "csv demand",
    "csv request",
    "csv ask",
    "csv inquire",
    "csv query",
    "csv question",
    "csv interrogate",
    "csv examine",
    "csv test",
    "csv quiz",
    "csv grill",
    "csv pump",
    "csv probe",
    "csv sound",
    "csv fathom",
    "csv plumb",
    "csv delve",
    "csv dig",
    "csv excavate",
    "csv mine",
    "csv quarry",
    "csv extract",
    "csv withdraw",
    "csv remove",
    "csv abstract",
    "csv separate",
    "csv isolate",
    "csv segregate",
    "csv sequester",
    "csv seclude",
    "csv cloister",
    "csv confine",
    "csv imprison",
    "csv incarcerate",
    "csv intern",
    "csv detain",
    "csv hold",
    "csv keep",
    "csv retain",
    "csv maintain",
    "csv preserve",
    "csv conserve",
    "csv save",
    "csv protect",
    "csv guard",
    "csv defend",
    "csv shield",
    "csv shelter",
    "csv harbor",
    "csv house",
    "csv accommodate",
    "csv lodge",
    "csv quarter",
    "csv billet",
    "csv canton",
    "csv encamp",
    "csv camp",
    "csv bivouac",
    "csv tent",
    "csv pup",
    "csv den",
    "csv lair",
    "csv nest",
    "csv roost",
    "csv perch",
    "csv rest",
    "csv repose",
    "csv relax",
    "csv unwind",
    "csv decompress",
    "csv destress",
    "csv unbend",
    "csv loosen up",
    "csv chill out",
    "csv cool down",
    "csv calm down",
    "csv settle down",
    "csv quiet down",
    "csv hush",
    "csv shush",
